---
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: default
  containers:
  - name: maven
    image: maven:3.3.9-jdk-8-alpine
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    env:
    - name: CONTAINER_ENV_VAR
      value: maven